version: "2.3"

services:
  server:
    build:
      context: .

    ports:
      - "$PORT:$PORT"

    environment:
      PORT: $PORT
      API_TOKEN: ${API_TOKEN}

  server-gpu:
    build:
      context: .
      dockerfile: Dockerfile_gpu    
    
    runtime: nvidia

    ports:
      - "$PORT:$PORT"

    environment:
      PORT: $PORT
      API_TOKEN: ${API_TOKEN